export const CarLightsMk = [
  {
    'name': 'Предупредувачко светло за температурата на моторот',
    'description': 'Индикаторското светло значи дека температурата на моторот ги надминала нормалните граници Проверете го нивото на течноста за ладење, работата на вентилаторот, капачето на радијаторот, истекувањето на течноста за ладење',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2019/06/GOFAR_car-dashboard-symbols-engine-temperature-warning-light.jpg',
    'image_path': require(
      '../assets/car-light/Engine_Temperature_Warning_Light.jpg'),
  },
  {
    'name': 'Предупредувачко светло за полнење на батеријата',
    'description': 'Индикаторското светло значи дека системот за полнење на автомобилот има недостаток на струја или не се полни правилно. Тоа нормално укажува на проблем со самата батерија или алтернаторот',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-battery-charge.jpg',
    'image_path': require(
      '../assets/car-light/Battery_Charge_Warning_Light.jpg'),
  },
  {
    'name': 'Предупредувачко светло за притисок на маслото',
    'description': 'Показното светло значи губење на притисокот на маслото, што значи дека подмачкувањето е ниско или целосно изгубено. Веднаш проверете го нивото и притисокот на маслото',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/283092_Car-Dashboard-Symbols_oil-pressure_090618.jpg',
    'image_path': require('../assets/car-light/Oil_Pressure_Warning_Light.jpg'),
  },
  {
    'name': 'Предупредувачко светло за сопирачките',
    'description': 'Индикаторското светло се вклучува кога рачната сопирачка е вклучена. )',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake.jpg',
    'image_path': require('../assets/car-light/Brake_Warning_Light.jpg'),
  },
  {
    'name': 'Предупредувачко светло за притисок на гумите',
    'description': 'Показното светло значи дека притисокот е низок во една од вашите гуми',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-time-pressure.jpg',
    'image_path': require(
      '../assets/car-light/Tire_Pressure_Warning_Light.jpg'),
  },
  {
    'name': 'Исклучена контрола на тракцијата',
    'description': 'Показното светло значи дека TCS (систем за контрола на влечење) на возилата е деактивиран.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-traction-control-off.jpg',
    'image_path': require('../assets/car-light/Traction_Control_Off.jpg'),
  },
  {
    'name': 'Заклучување на воланот',
    'description': 'Показното светло значи дека воланот ви е заклучен и не може да се поместува За да ја исклучите бравата на воланот, вметнете го клучот во палењето и свртете го барем на првата позиција додека го вртите воланот во која било насока',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-steering-wheel-lock.jpg',
    'image_path': require('../assets/car-light/Steering_Wheel_Lock.jpg'),
  },
  {
    'name': 'Предупредување за влечење на приколката',
    'description': 'Показните светла значат дека куката за влечење е отклучена или дека има проблем со системот за осветлување.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-trailer-tow-hitch-warning.jpg',
    'image_path': require('../assets/car-light/Trailer_Tow_Hitch_Warning.jpg'),
  },
  {
    'name': 'Светло за контрола на тракцијата',
    'description': 'Показното светло се вклучува кога се активира TCS (систем за контрола на тракцијата) на возилото.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-traction-control-light.jpg',
    'image_path': require('../assets/car-light/Traction_Control_Light.jpg'),
  },
  {
    'name': 'Сервисно возило наскоро',
    'description': 'Индикаторското светло се вклучува кога има дефект во областа на системите на шасијата на возилото, како што се - системот за сопирање против блокирање (ABS), системот за контрола на тракцијата (TCS), електронскиот систем за суспензија или хидрауличниот систем на сопирачките',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-sevice-vehicle-soon.jpg',
    'image_path': require('../assets/car-light/Service_Vehicle_Soon.jpg'),
  },
  {
    'name': 'Безбедносно предупредување',
    'description': 'Показното светло за момент ќе се вклучи ако прекинувачот за палење е заклучен и ќе му треба соодветно',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-security-alert.jpg',
    'image_path': require('../assets/car-light/Security_Alert.jpg'),
  },
  {
    'name': 'Странично воздушно перниче',
    'description': 'Показното светло значи дефект на страничното воздушно перниче',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-side-airbag.jpg',
    'image_path': require('../assets/car-light/Side_Airbag.jpg'),
  },
  {
    'name': 'Предупредување за намалена моќност',
    'description': 'Индикаторското светло значи дека моторниот компјутер има ограничена излезна моќност на моторот.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-reduced-power-warning.jpg',
    'image_path': require('../assets/car-light/Reduced_Power_Warning.jpg'),
  },
  {
    'name': 'Индикатор за безбедносниот појас',
    'description': 'Показното светло значи дека не е прицврстен појас за патник во возилото.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-seat-belt.jpg',
    'image_path': require('../assets/car-light/Seat_Belt_Indicator.jpg'),
  },
  {
    'name': 'Притиснете ја педалата за спојката',
    'description': 'Индикатор за туркање на спојката',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-press-clutch-pedal.jpg',
    'image_path': require('../assets/car-light/Press_Clutch_Pedal.jpg'),
  },
  {
    'name': 'Дефект на погонската единица',
    'description': 'Показното светло се вклучува кога е откриен дефект на погонската единица или AWD Контактирајте со вашиот механичар што е можно поскоро.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-powertrain-fault.jpg',
    'image_path': require('../assets/car-light/Powertrain Fault.jpg'),
  },
  {
    'name': 'Притиснете ја педалата на сопирачката',
    'description': 'Индикатор за притискање на педалата на сопирачката',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-press-brake-pedal.jpg',
    'image_path': require('../assets/car-light/Press_Brake_Pedal.jpg'),
  },
  {
    'name': 'Светло на паркирната сопирачка',
    'description': 'Показното светло значи вклучена сопирачка за паркирање',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-parking-brake-light.jpg',
    'image_path': require('../assets/car-light/Parking_Brake_Light.jpg'),
  },
  {
    'name': 'Overdrive Light',
    'description': 'Показното светло значи дека системот за пребрзување на возилото е рачно исклучен.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-overdrive-light.jpg',
    'image_path': require('../assets/car-light/Overdrive_Light.jpg'),
  },
  {
    'name': 'Потсетник за промена на маслото',
    'description': 'Показното светло значи дека векот на маслото е истечен',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-oil-change.jpg',
    'image_path': require('../assets/car-light/Oil_Change_Reminder.jpg'),
  },
  {
    'name': 'Главна светилка за предупредување',
    'description': 'Индикаторското светло обично придружено со друго предупредувачко светло и покажува дека еден или повеќе системи за предупредување биле',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-master-warning.jpg',
    'image_path': require('../assets/car-light/Master_Warning_Light.jpg'),
  },
  {
    'name': 'Информативно предупредувачко светло',
    'description': 'Показното светло ќе се вклучи кога ќе се зачува нова порака на информативниот екран. Ќе биде црвено или жолто',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-information-light-warning.jpg',
    'image_path': require('../assets/car-light/Information_Warning_Light.jpg'),
  },
  {
    'name': 'Предупредувачко светло за мраз на патот',
    'description': 'Индикаторското светло се вклучува кога надворешниот воздух ќе почне да достигнува ниски температури, околу 35°F или 3°C.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-icy-road-warning-light.jpg',
    'image_path': require('../assets/car-light/Icy_Road_Warning_Light.jpg'),
  },
  {
    'name': 'Капаче за гас / гориво',
    'description': 'Показното светло се вклучува ако капачето за гас/гориво не е правилно затегнато.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-gas-cap.jpg',
    'image_path': require('../assets/car-light/Gas_Fuel_Cap.jpg'),
  },
  {
    'name': 'Предупредување за далечина',
    'description': 'Показното светло значи дека возилото напред е премногу блиску или пребрзо му се приближува или дека е во мирување',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-distance-warning.jpg',
    'image_path': require('../assets/car-light/Distance_Warning.jpg'),
  },
  {
    'name': 'Затнат филтер за воздух',
    'description': 'Показното светло се вклучува кога има намален проток на воздух кон моторот Нека го замени или прегледа филтерот за воздух.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-clogged-air-filter.jpg',
    'image_path': require('../assets/car-light/Clogged_Air_Filter.jpg'),
  },
  {
    'name': 'Безбедносна брава за деца',
    'description': 'Показното светло значи дека е активна безбедносната брава за деца',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-child-safety-lock.jpg',
    'image_path': require('../assets/car-light/Child_Safety_Lock.jpg'),
  },
  {
    'name': 'Проверете го моторот или индикаторското светло за дефект (MIL)',
    'description': 'Показното светло се вклучува секогаш кога моторот е вклучен за да се провери сијалицата Ако светилката останува запалена,',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-check-engine.jpg',
    'image_path': require(
      '../assets/car-light/Check_Engine_or_Malfunction_Indicator_Light_(MIL).jpg'),
  },
  {
    'name': 'Предупредување од каталитички конвертор',
    'description': 'Показното светло значи дека катализаторот или се прегрева или не работи како што е предвидено.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-catalytic-converter-warning.jpg',
    'image_path': require(
      '../assets/car-light/Catalytic_Converter_Warning.jpg'),
  },
  {
    'name': 'Течност за сопирачки',
    'description': 'Показното светло значи дека нивото на течноста за сопирачките е ниско',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake-fluid.jpg',
    'image_path': require('../assets/car-light/Brake_Fluid.jpg'),
  },
  {
    'name': 'Предупредување за влошки за сопирачките',
    'description': 'Показното светло значи дека се истрошени влошките на сопирачките',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake-pad.jpg',
    'image_path': require('../assets/car-light/Brake_Pad_Warning.jpg'),
  },
  {
    'name': 'Предупредување за светлата на сопирачките',
    'description': 'Показното светло значи дека надворешната сијалица на сопирачките е неисправна Проверете ја работата на целото надворешно стоп светло',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake-lights-warning.jpg',
    'image_path': require('../assets/car-light/Brake_Lights_Warning.jpg'),
  },
  {
    'name': 'Предупредување за автоматски менувач',
    'description': 'Показното светло значи дека има дефект на менувачот/преносот.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-automatic-gearbox-warning.jpg',
    'image_path': require('../assets/car-light/Automatic_Gearbox_Warning.jpg'),
  },
  {
    'name': 'Систем за сопирање против блокирање (ABS)',
    'description': 'Показното светло значи дека може да има дефект во системот ABS',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-anti-lock-braking-system.jpg',
    'image_path': require(
      '../assets/car-light/Anti-lock_Braking_System_(ABS).jpg'),
  },
  {
    'name': 'Погон на сите тркала (AWD/4WD)',
    'description': 'Показното светло се вклучува кога има дефект со системот 4WD.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-all-wheel-drive.jpg',
    'image_path': require('../assets/car-light/All_Wheel_Drive_(AWD_4WD).jpg'),
  },
  {
    'name': 'Индикатор за воздушно перниче',
    'description': 'Показното светло се вклучува кога е исклучено предното воздушно перниче Ако свети или трепка оваа светилка има дефект во',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-airbag.jpg',
    'image_path': require('../assets/car-light/Airbag_Indicator.jpg'),
  },
  {
    'name': 'Воздушното перниче е деактивирано',
    'description': 'Показното светло се вклучува кога има дефект во системот на задниот спојлер.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-airbag-deactivated.jpg',
    'image_path': require('../assets/car-light/Airbag_Deactivated.jpg'),
  },
  {
    'name': 'Адаптивни амортизери за суспензија',
    'description': 'Показното светло значи дека треба да се контактирате со овластен сервисер.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adaptive-suspension-dampers.jpg',
    'image_path': require(
      '../assets/car-light/Adaptive_Suspension_Dampers.jpg'),
  },
  {
    'name': 'Индикаторско светло за заклучување на 4 тркала (4WD).',
    'description': 'Показното светло значи дека е активиран режимот 4WD Lock на возилото.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-4WD-lock-indicator.jpg',
    'image_path': require(
      '../assets/car-light/4_Wheel_Drive_(4WD)_LOCK_Indicator_Light.jpg'),
  },
  {
    'name': 'Индикаторско светло за кратко светло',
    'description': 'Показното светло значи дека средното светло на возилата е вклучено',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-low-beam-indicator-light.jpg',
    'image_path': require('../assets/car-light/Low_Beam_Indicator_Light.jpg'),
  },
  {
    'name': 'Исклучена светилка',
    'description': 'Показното светло значи дека има надворешно светло на возилото кое не функционира правилно.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-lamp-out.jpg',
    'image_path': require('../assets/car-light/Lamp_Out.jpg'),
  },
  {
    'name': 'Дефект на ESP/Неисправност на контролата на влечење',
    'description': 'Показното светло значи дека има проблем со контролата на тракцијата на возилото.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-esp-fault-traction-control-malfunction.jpg',
    'image_path': require(
      '../assets/car-light/ESP_Fault_Traction_Control_Malfunction.jpg'),
  },
  {
    'name': 'Електрична сопирачка за паркирање',
    'description': 'Показното светло се вклучува кога електричната сопирачка за паркирање има дефект.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-electric-park-brake.jpg',
    'image_path': require('../assets/car-light/Electric_Park_Brake.jpg'),
  },
  {
    'name': 'Индикатор за светло за долго светло',
    'description': 'Показното светло значи дека долгото светло на вашиот автомобил се запалени или ако се користи функцијата за блиц на долгото светло.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-high-beam-light-indicator.jpg',
    'image_path': require('../assets/car-light/High_Beam_Light_Indicator.jpg'),
  },
  {
    'name': 'Контрола на опсегот на фаровите',
    'description': 'Показното светло се вклучува ако се открие проблем со системот за контрола на опсегот на фаровите.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-headlight-range-control.jpg',
    'image_path': require('../assets/car-light/Headlight_Range_Control.jpg'),
  },
  {
    'name': 'Предни светла за магла',
    'description': 'Индикаторското светло значи дека предните светла за магла се вклучени',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-front-fog-light.jpg',
    'image_path': require('../assets/car-light/Front_Fog_Lights.jpg'),
  },
  {
    'name': 'Дефект на надворешното светло',
    'description': 'Показното светло значи дека секое надворешно светло на вашиот автомобил не работи',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-exterior-light-fault.jpg',
    'image_path': require('../assets/car-light/Exterior_Light_Fault.jpg'),
  },
  {
    'name': 'Автоматско долго светло',
    'description': 'Индикаторското светло значи дека системот за автоматско долго светло ги вклучил фаровите за долгото светло.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-auto-high-beam.jpg',
    'image_path': require('../assets/car-light/Auto_High_Beam.jpg'),
  },
  {
    'name': 'Систем за адаптивна светлина',
    'description': 'Показното светло ќе светне кога ќе се вклучат приспособливите фарови',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adaptive-light-system.jpg',
    'image_path': require('../assets/car-light/Adaptive_Light_System.jpg'),
  },
  {
    'name': 'Индикатор за странично светло',
    'description': 'Показното светло ќе се вклучи кога се користат вообичаените фарови',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-side-light-indicator-light.jpg',
    'image_path': require('../assets/car-light/Side_Light_Indicator.jpg'),
  },
  {
    'name': 'Вклучени задни светла за магла',
    'description': 'Показното светло значи дека задните светла за магла се вклучени',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-rear-fog-lights.jpg',
    'image_path': require(
      '../assets/car-light/Rear_Fog_Lights_Switched_On.jpg'),
  },
  {
    'name': 'Сензор за дожд и светлина',
    'description': 'Показното светло значи дека има проблем со сензорскиот систем. Бришачите и светлата нема да функционираат',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-rain-and-light-sensor.jpg',
    'image_path': require('../assets/car-light/Rain_and_Light_Sensor.jpg'),
  },
  {
    'name': 'Одмрзнување на шофершајбната',
    'description': '        Показното светло значи дека одмрзнувањето на прозорецот е во функција.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-windshield-defrost.jpg',
    'image_path': require('../assets/car-light/Windshield_Defrost.jpg'),
  },
  {
    'name': 'Воздушна суспензија',
    'description': 'Индикаторското светло значи дека има проблем со кесите со воздушна суспензија, најверојатно поради истекување или проблем со надувување.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-air-suspension.jpg',
    'image_path': require('../assets/car-light/Air_Suspension.jpg'),
  },
  {
    'name': 'Потсетник за течност за миење',
    'description': 'Показното светло покажува дали резервоарот за течност за миење на шофершајбната е речиси празен Наполнете го резервоарот за течност за миење.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-water-fluid-reminder.jpg',
    'image_path': require('../assets/car-light/Washer_Fluid_Reminder.jpg'),
  },
  {
    'name': 'Одмрзнување на задниот прозорец',
    'description': 'Показното светло значи дека работи одмрзнувањето на задното стакло',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-rear-window-defrost.jpg',
    'image_path': require('../assets/car-light/Rear_Window_Defrost.jpg'),
  },
  {
    'name': 'Ниско ниво на гориво',
    'description': 'Индикаторското светло значи дека на автомобилот му недостасува гориво и наскоро ќе треба да се наполни.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-low-fuel-level.jpg',
    'image_path': require('../assets/car-light/Low_Fuel_Level.jpg'),
  },
  {
    'name': 'Клучот не е во возилото',
    'description': 'Показното светло значи дека клучот не е во автомобилот',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-key-not-in-vehicle.jpg',
    'image_path': require('../assets/car-light/Key_Not_in_Vehicle.jpg'),
  },
  {
    'name': 'Отворена хауба/хауба',
    'description': 'Показното светло значи дека хаубата на автомобилот не е правилно затворена',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-hood-bonnet-open.jpg',
    'image_path': require('../assets/car-light/Hood_Bonnet_Open.jpg'),
  },
  {
    'name': 'Запалени светла за опасност',
    'description': 'Показното светло значи дека светлата за опасност се вклучени',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-hazard-lights-on.jpg',
    'image_path': require('../assets/car-light/Hazard_Lights_On.jpg'),
  },
  {
    'name': 'Вентилатор',
    'description': 'Показното светло значи дека внатрешната вентилација/вентилатор работи.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-fan-green.jpg',
    'image_path': require('../assets/car-light/Fan.jpg'),
  },
  {
    'name': 'Подотворена врата',
    'description': 'Показното светло се вклучува кога една или повеќе врати од автомобилот не се правилно затворени.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-door-ajar.jpg',
    'image_path': require('../assets/car-light/Door_Ajar.jpg'),
  },
  {
    'name': 'Индикатори за насока/сигнал',
    'description': 'Показното светло значи дека еден од трепкачите (лево или десно) е активиран.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-direction-signal-indicators.jpg',
    'image_path': require(
      '../assets/car-light/Direction_Signal_Indicators.jpg'),
  },
  {
    'name': 'Автомобил на рампата',
    'description': 'Показното светло значи дека возилото е на систем на рампа/дигалка',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-car-on-ramp.jpg',
    'image_path': require('../assets/car-light/Car_on_Ramp.jpg'),
  },
  {
    'name': 'Предупредувачко светло за серво волан',
    'description': 'Показното светло се вклучува ако има проблем со системот за серво волан и ќе биде оневозможено додека не се поправи.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-power-steering-warning.jpg',
    'image_path': require(
      '../assets/car-light/Power_Steering_Warning_Light.jpg'),
  },
  {
    'name': 'Рециркулиран воздух во кабината',
    'description': '        Показното светло значи дека системот за вентилација на возилото го рециркулира воздухот од внатрешноста на возилото,',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-recirculated-cabin-air.jpg',
    'image_path': require('../assets/car-light/Recirculated_Cabin_Air.jpg'),
  },
  {
    'name': 'Предупредување за заден спојлер',
    'description': 'Показното светло се вклучува кога има дефект во системот на задниот спојлер.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-rear-spoiler-warning.jpg',
    'image_path': require('../assets/car-light/Rear_Spoiler_Warning.jpg'),
  },
  {
    'name': 'Паркирање со помошен пилот за паркирање',
    'description': 'Показното светло значи дека е вклучен PAP (Park Assist Pilot).',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-parking-with-park-assist-pilot.jpg',
    'image_path': require(
      '../assets/car-light/Parking_with_Park_Assist_Pilot.jpg'),
  },
  {
    'name': 'Предупредување за заминување од лента',
    'description': 'Индикаторското светло значи дека возилото се движи надвор од сегашната лента без сигнализација.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-lane-departure-warning.jpg',
    'image_path': require('../assets/car-light/Lane_Departure_Warning.jpg'),
  },
  {
    'name': 'Помош за лента',
    'description': 'Показното светло се вклучува кога е вклучен системот за помош на лентата и може да се откријат ознаки на патиштата.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-lane-assist.jpg',
    'image_path': require('../assets/car-light/Lane_Assist.jpg'),
  },
  {
    'name': 'Слаба на батеријата за клучеви',
    'description': 'Показното светло ви дава до знаење кога треба да се смени и замени батеријата за клучеви, за да можете да продолжите да ја користите',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-key-fob-battery-low.jpg',
    'image_path': require('../assets/car-light/Key_Fob_Battery_Low.jpg'),
  },
  {
    'name': 'Предупредување на прекинувачот за палење',
    'description': 'Показното светло значи дека има проблем со системот за палење или клучот од автомобилот, може да се должи на дефект или истрошеност',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-ignition-switch-warning.jpg',
    'image_path': require('../assets/car-light/Ignition_Switch_Warning.jpg'),
  },
  {
    'name': 'Контрола на спуштање на рид',
    'description': 'Показното светло се вклучува кога системот е активиран и ви помага да одржувате одредена брзина додека возите надолу a',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-hill-descent-control.jpg',
    'image_path': require('../assets/car-light/Hill_Descent_Control.jpg'),
  },
  {
    'name': 'Температура на пренос',
    'description': 'Индикаторското светло значи дека температурата на моторот ги надминала нормалните граници Проверете го нивото на течноста за ладење, работата на вентилаторот, капачето на радијаторот, истекувањето на течноста за ладење',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-transmission-temp.jpg',
    'image_path': require('../assets/car-light/Transmission_Temperature.jpg'),
  },
  {
    'name': 'Предупредување за преден судир',
    'description': 'Показното светло се вклучува кога ќе се открие потенцијален судир',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-forward-collision.jpg',
    'image_path': require('../assets/car-light/Forward_Collision_Warning.jpg'),
  },
  {
    'name': 'Индикатор за еко возење',
    'description': 'Показното светло ќе се вклучи кога ќе се активира Eco функцијата',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-eco-driving-indicator.jpg',
    'image_path': require('../assets/car-light/Eco_Driving_Indicator.jpg'),
  },
  {
    'name': 'Контрола на крстарење',
    'description': 'Показното светло значи дека системот за контрола на патувањето е активиран',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-cruise-control.jpg',
    'image_path': require('../assets/car-light/Cruise_Control.jpg'),
  },
  {
    'name': 'Конвертибилно предупредувачко светло за покривот',
    'description': 'Показното светло ќе се вклучи додека покривот се отвора или затвора Ако светилката постојано свети, покривот е',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-convertible-roof-warning-light.jpg',
    'image_path': require(
      '../assets/car-light/Convertible_Roof_Warning_Light.jpg'),
  },
  {
    'name': 'Индикаторско светло за задржување на сопирачките',
    'description': 'Показното светло значи дека системот за задржување на сопирачките функционира правилно.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake-hold-indicator.jpg',
    'image_path': require('../assets/car-light/Brake_Hold_Indicator_Light.jpg'),
  },
  {
    'name': 'Светло за индикатор за слепа точка',
    'description': 'Показното светло се вклучува кога ќе се открие возило или пречка во мртвата точка.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-blind-spot-indicator.jpg',
    'image_path': require('../assets/car-light/Blind_Spot_Indicator_Light.jpg'),
  },
  {
    'name': 'Автоматско бришење на шофершајбната',
    'description': 'Показното светло значи дека бришачите на шофершајбната работат во автоматскиот режим.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-auto-windscreen-wiping.jpg',
    'image_path': require('../assets/car-light/Auto_Windscreen_Wiping.jpg'),
  },
  {
    'name': 'Автоматско сопирање за итни случаи (AEB)',
    'description': 'Индикаторското светло се вклучува кога системот AEB е исклучен или кога радарскиот сензор или капакот е блокиран со нечистотија или',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-automatic-emegency-braking.jpg',
    'image_path': require(
      '../assets/car-light/Automatic_Emergency_Braking_(AEB).jpg'),
  },
  {
    'name': 'Адаптивна контрола на патувањето',
    'description': 'Показното светло значи дека ACC (Adaptive Cruise Control) работи.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adaptive-cruise-control.jpg',
    'image_path': require('../assets/car-light/Adaptive_Cruise_Control.jpg'),
  },
  {
    'name': 'Зимски режим',
    'description': 'Показното светло ви дава до знаење дека возите во зимски режим',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-winter-mode.jpg',
    'image_path': require('../assets/car-light/Winter_Mode.jpg'),
  },
  {
    'name': 'Предупредувачко светло за почеток/стоп',
    'description': 'Показното светло се вклучува за да го информира возачот дека интелигентниот систем за запирање / стартување е активен и дека моторот е',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-start-stop-warning.jpg',
    'image_path': require('../assets/car-light/Start_Stop_Warning_Light.jpg'),
  },
  {
    'name': 'Ограничувач на брзина',
    'description': 'Показното светло значи дека функцијата за ограничување на брзината е активирана',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-speed-limiter.jpg',
    'image_path': require('../assets/car-light/Speed_Limiter.jpg'),
  },
  {
    'name': 'Температура на седиштето',
    'description': 'Показното светло значи дека протокот на воздух се распределува помеѓу предното странично стакло, шофершајбната и одмаглувањето на просторот за нозете',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-seat-temperature.jpg',
    'image_path': require('../assets/car-light/Seat_Temperature.jpg'),
  },
  {
    'name': 'Индикатор за приклучок за сјај',
    'description': 'Индикаторското светло значи дека приклучоците за осветлување на моторот се загреваат и дека моторот не треба да се запали додека',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-glow-plug.jpg',
    'image_path': require('../assets/car-light/Glow_Plug_Indicator.jpg'),
  },
  {
    'name': 'Предупредување за филтер за гориво',
    'description': 'Показното светло значи дека филтерот за дизел гориво е полн и треба да се испразни за да се избегне оштетување на моторот.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-fuel-filter-warning.jpg',
    'image_path': require('../assets/car-light/Fuel_Filter_Warning.jpg'),
  },
  {
    'name': 'Издувна течност',
    'description': 'Индикаторското светло значи дека резервоарот за издувната течност на дизелот има малку течност.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-exhaust-fluid.jpg',
    'image_path': require('../assets/car-light/Exhaust_Fluid.jpg'),
  },
  {
    'name': 'Резервоарот на AdBlue е празен',
    'description': 'Показното светло значи дека треба да го наполните резервоарот со повеќе издувна течност.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adblue-tank-empty.jpg',
    'image_path': require('../assets/car-light/AdBlue_Tank_is_Empty.jpg'),
  },
  {
    'name': 'Неисправност на AdBlue',
    'description': 'Показното светло значи дека или системот AdBlue не функционира или системот не е исполнет со стандардниот',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adblue-tank-malfunction.jpg',
    'image_path': require('../assets/car-light/AdBlue_Malfunction.jpg'),
  },
  {
    'name': 'Предупредување за филтер за течност за вода',
    'description': 'Показното светло значи дека водата во филтерот за гориво го достигнала максималниот капацитет Исцедете ја водата од филтерот.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-water-fluid-filter.jpg',
    'image_path': require('../assets/car-light/Water_Fluid_Filter_Warning.jpg'),
  },
]
