export const CityInfos = [
  {
    'city': 'Skopje',
    'latitude': '41.9833',
    'longitude': '21.4333',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Skopje',
    'capital': 'primary',
    'population': '640000',
    'population_proper': '640000',
  },
  {
    'city': 'Tetovo',
    'latitude': '42.0103',
    'longitude': '20.9714',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Tetovo',
    'capital': 'admin',
    'population': '142030',
    'population_proper': '142030',
  },
  {
    'city': 'Bitola',
    'latitude': '41.0319',
    'longitude': '21.3347',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Bitola',
    'capital': 'admin',
    'population': '74550',
    'population_proper': '74550',
  },
  {
    'city': 'Kumanovo',
    'latitude': '42.1322',
    'longitude': '21.7144',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Kumanovo',
    'capital': 'admin',
    'population': '70842',
    'population_proper': '70842',
  },
  {
    'city': 'Prilep',
    'latitude': '41.3464',
    'longitude': '21.5542',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Prilep',
    'capital': 'admin',
    'population': '66246',
    'population_proper': '66246',
  },
  {
    'city': 'Ohrid',
    'latitude': '41.1169',
    'longitude': '20.8019',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Ohrid',
    'capital': 'admin',
    'population': '55749',
    'population_proper': '55749',
  },
  {
    'city': 'Strumica',
    'latitude': '41.4375',
    'longitude': '22.6431',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Strumica',
    'capital': 'admin',
    'population': '45087',
    'population_proper': '45087',
  },
  {
    'city': 'Veles',
    'latitude': '41.7153',
    'longitude': '21.7753',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Veles',
    'capital': 'admin',
    'population': '43716',
    'population_proper': '43716',
  },
  {
    'city': 'Štip',
    'latitude': '41.7358',
    'longitude': '22.1914',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Štip',
    'capital': 'admin',
    'population': '43652',
    'population_proper': '43652',
  },
  {
    'city': 'Kavadarci',
    'latitude': '41.4328',
    'longitude': '22.0117',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Kavadarci',
    'capital': 'admin',
    'population': '38741',
    'population_proper': '38741',
  },
  {
    'city': 'Gostivar',
    'latitude': '41.8000',
    'longitude': '20.9167',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Gostivar',
    'capital': 'admin',
    'population': '35847',
    'population_proper': '35847',
  },
  {
    'city': 'Kočani',
    'latitude': '41.9167',
    'longitude': '22.4125',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Kočani',
    'capital': 'admin',
    'population': '28330',
    'population_proper': '28330',
  },
  {
    'city': 'Kičevo',
    'latitude': '41.5142',
    'longitude': '20.9631',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Kičevo',
    'capital': 'admin',
    'population': '27067',
    'population_proper': '27067',
  },
  {
    'city': 'Struga',
    'latitude': '41.1775',
    'longitude': '20.6789',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Struga',
    'capital': 'admin',
    'population': '16559',
    'population_proper': '16559',
  },
  {
    'city': 'Radoviš',
    'latitude': '41.6381',
    'longitude': '22.4644',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Radoviš',
    'capital': 'admin',
    'population': '16223',
    'population_proper': '16223',
  },
  {
    'city': 'Gevgelija',
    'latitude': '41.1392',
    'longitude': '22.5025',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Gevgelija',
    'capital': 'admin',
    'population': '15685',
    'population_proper': '15685',
  },
  {
    'city': 'Debar',
    'latitude': '41.5250',
    'longitude': '20.5272',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Debar',
    'capital': 'admin',
    'population': '14561',
    'population_proper': '14561',
  },
  {
    'city': 'Kriva Palanka',
    'latitude': '42.2017',
    'longitude': '22.3317',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Kriva Palanka',
    'capital': 'admin',
    'population': '14558',
    'population_proper': '14558',
  },
  {
    'city': 'Sveti Nikole',
    'latitude': '41.8650',
    'longitude': '21.9425',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Sveti Nikole',
    'capital': 'admin',
    'population': '13746',
    'population_proper': '13746',
  },
  {
    'city': 'Negotino',
    'latitude': '41.4839',
    'longitude': '22.0892',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Negotino',
    'capital': 'admin',
    'population': '13284',
    'population_proper': '13284',
  },
  {
    'city': 'Delčevo',
    'latitude': '41.9661',
    'longitude': '22.7747',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Delčevo',
    'capital': 'admin',
    'population': '11500',
    'population_proper': '11500',
  },
  {
    'city': 'Vinica',
    'latitude': '41.8828',
    'longitude': '22.5092',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Vinica',
    'capital': 'admin',
    'population': '10863',
    'population_proper': '10863',
  },
  {
    'city': 'Probištip',
    'latitude': '41.9936',
    'longitude': '22.1767',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Probištip',
    'capital': 'admin',
    'population': '10826',
    'population_proper': '10826',
  },
  {
    'city': 'Aračinovo',
    'latitude': '42.0264',
    'longitude': '21.5617',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Aračinovo',
    'capital': 'admin',
    'population': '7315',
    'population_proper': '7315',
  },
  {
    'city': 'Berovo',
    'latitude': '41.7078',
    'longitude': '22.8564',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Berovo',
    'capital': 'admin',
    'population': '7002',
    'population_proper': '7002',
  },
  {
    'city': 'Kratovo',
    'latitude': '42.0783',
    'longitude': '22.1750',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Kratovo',
    'capital': 'admin',
    'population': '6924',
    'population_proper': '6924',
  },
  {
    'city': 'Bogovinje',
    'latitude': '41.9233',
    'longitude': '20.9133',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Bogovinje',
    'capital': 'admin',
    'population': '6328',
    'population_proper': '6328',
  },
  {
    'city': 'Bogdanci',
    'latitude': '41.2031',
    'longitude': '22.5728',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Bogdanci',
    'capital': 'admin',
    'population': '6031',
    'population_proper': '6031',
  },
  {
    'city': 'Studeničani',
    'latitude': '41.9158',
    'longitude': '21.5306',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Studeničani',
    'capital': 'admin',
    'population': '5786',
    'population_proper': '5786',
  },
  {
    'city': 'Sopište',
    'latitude': '41.9500',
    'longitude': '21.4333',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Sopište',
    'capital': 'admin',
    'population': '5554',
    'population_proper': '5554',
  },
  {
    'city': 'Kruševo',
    'latitude': '41.3700',
    'longitude': '21.2483',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Kruševo',
    'capital': 'admin',
    'population': '5507',
    'population_proper': '5507',
  },
  {
    'city': 'Vrapčište',
    'latitude': '41.8337',
    'longitude': '20.8851',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Vrapčište',
    'capital': 'admin',
    'population': '4874',
    'population_proper': '4874',
  },
  {
    'city': 'Valandovo',
    'latitude': '41.3169',
    'longitude': '22.5611',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Valandovo',
    'capital': 'admin',
    'population': '4442',
    'population_proper': '4442',
  },
  {
    'city': 'Želino',
    'latitude': '41.9794',
    'longitude': '21.0619',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Želino',
    'capital': 'admin',
    'population': '4110',
    'population_proper': '4110',
  },
  // {
  //   'city': 'Tearce',
  //   'latitude': '42.0775',
  //   'longitude': '21.0519',
  //   'country': 'Macedonia',
  //   'iso2': 'MK',
  //   'admin_name': 'Tearce',
  //   'capital': 'admin',
  //   'population': '4004',
  //   'population_proper': '4004',
  // },
  {
    'city': 'Makedonski Brod',
    'latitude': '41.5133',
    'longitude': '21.2153',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Makedonski Brod',
    'capital': 'admin',
    'population': '3740',
    'population_proper': '3740',
  },
  {
    'city': 'Demir Kapija',
    'latitude': '41.4114',
    'longitude': '22.2422',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Demir Kapija',
    'capital': 'admin',
    'population': '3394',
    'population_proper': '3394',
  },
  {
    'city': 'Pehčevo',
    'latitude': '41.7592',
    'longitude': '22.8906',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Pehčevo',
    'capital': 'admin',
    'population': '3237',
    'population_proper': '3237',
  },
  {
    'city': 'Brvenica',
    'latitude': '41.9667',
    'longitude': '20.9833',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Brvenica',
    'capital': 'admin',
    'population': '2918',
    'population_proper': '2918',
  },
  {
    'city': 'Novo Selo',
    'latitude': '41.4128',
    'longitude': '22.8800',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Novo Selo',
    'capital': 'admin',
    'population': '2829',
    'population_proper': '2829',
  },
  {
    'city': 'Vevčani',
    'latitude': '41.2403',
    'longitude': '20.5931',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Vevčani',
    'capital': 'admin',
    'population': '2706',
    'population_proper': '2706',
  },
  {
    'city': 'Petrovec',
    'latitude': '41.9333',
    'longitude': '21.6167',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Petrovec',
    'capital': 'admin',
    'population': '2659',
    'population_proper': '2659',
  },
  {
    'city': 'Lipkovo',
    'latitude': '42.1553',
    'longitude': '21.5875',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Lipkovo',
    'capital': 'admin',
    'population': '2644',
    'population_proper': '2644',
  },
  {
    'city': 'Demir Hisar',
    'latitude': '41.2208',
    'longitude': '21.2031',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Demir Hisar',
    'capital': 'admin',
    'population': '2593',
    'population_proper': '2593',
  },
  {
    'city': 'Rosoman',
    'latitude': '41.5161',
    'longitude': '21.9497',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Rosoman',
    'capital': 'admin',
    'population': '2554',
    'population_proper': '2554',
  },
  {
    'city': 'Plasnica',
    'latitude': '41.4667',
    'longitude': '21.1167',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Plasnica',
    'capital': 'admin',
    'population': '2513',
    'population_proper': '2513',
  },
  {
    'city': 'Mogila',
    'latitude': '41.1083',
    'longitude': '21.3786',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Mogila',
    'capital': 'admin',
    'population': '2510',
    'population_proper': '2510',
  },
  {
    'city': 'Krivogaštani',
    'latitude': '41.3358',
    'longitude': '21.3331',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Krivogaštani',
    'capital': 'admin',
    'population': '2380',
    'population_proper': '2380',
  },
  {
    'city': 'Zrnovci',
    'latitude': '41.8542',
    'longitude': '22.4442',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Zrnovci',
    'capital': 'admin',
    'population': '2318',
    'population_proper': '2318',
  },
  {
    'city': 'Gradsko',
    'latitude': '41.5775',
    'longitude': '21.9428',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Gradsko',
    'capital': 'admin',
    'population': '2219',
    'population_proper': '2219',
  },
  {
    'city': 'Vasilevo',
    'latitude': '41.4758',
    'longitude': '22.6417',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Vasilevo',
    'capital': 'admin',
    'population': '2174',
    'population_proper': '2174',
  },
  {
    'city': 'Bosilovo',
    'latitude': '41.4406',
    'longitude': '22.7278',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Bosilovo',
    'capital': 'admin',
    'population': '1755',
    'population_proper': '1755',
  },
  {
    'city': 'Staro Nagoričane',
    'latitude': '42.2000',
    'longitude': '21.8300',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Staro Nagoričane',
    'capital': 'admin',
    'population': '1528',
    'population_proper': '1528',
  },
  {
    'city': 'Rankovce',
    'latitude': '42.1817',
    'longitude': '22.1228',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Rankovce',
    'capital': 'admin',
    'population': '1441',
    'population_proper': '1441',
  },
  {
    'city': 'Novaci',
    'latitude': '41.0419',
    'longitude': '21.4561',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Novaci',
    'capital': 'admin',
    'population': '1405',
    'population_proper': '1405',
  },
  {
    'city': 'Konče',
    'latitude': '41.4958',
    'longitude': '22.3825',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Konče',
    'capital': 'admin',
    'population': '1335',
    'population_proper': '1335',
  },
  {
    'city': 'Obleševo',
    'latitude': '41.8833',
    'longitude': '22.3339',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Češinovo-Obleševo',
    'capital': 'admin',
    'population': '1228',
    'population_proper': '1228',
  },
  {
    'city': 'Belčišta',
    'latitude': '41.3028',
    'longitude': '20.8303',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Debarca',
    'capital': 'admin',
    'population': '1203',
    'population_proper': '1203',
  },
  // {
  //   'city': 'Jegunovce',
  //   'latitude': '42.0731',
  //   'longitude': '21.1231',
  //   'country': 'Macedonia',
  //   'iso2': 'MK',
  //   'admin_name': 'Jegunovce',
  //   'capital': 'admin',
  //   'population': '1194',
  //   'population_proper': '1194',
  // },
  {
    'city': 'Lozovo',
    'latitude': '41.7817',
    'longitude': '21.9025',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Lozovo',
    'capital': 'admin',
    'population': '959',
    'population_proper': '959',
  },
  {
    'city': 'Dolneni',
    'latitude': '41.4264',
    'longitude': '21.4536',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Dolneni',
    'capital': 'admin',
    'population': '900',
    'population_proper': '900',
  },
  {
    'city': 'Rostuša',
    'latitude': '41.6100',
    'longitude': '20.6000',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Mavrovo i Rostuša',
    'capital': 'admin',
    'population': '872',
    'population_proper': '872',
  },
  {
    'city': 'Centar Župa',
    'latitude': '41.4775',
    'longitude': '20.5578',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Centar Župa',
    'capital': 'admin',
    'population': '800',
    'population_proper': '800',
  },
  {
    'city': 'Zelenikovo',
    'latitude': '41.8867',
    'longitude': '21.5869',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Zelenikovo',
    'capital': 'admin',
    'population': '771',
    'population_proper': '771',
  },
  {
    'city': 'Čučer-Sandevo',
    'latitude': '42.0975',
    'longitude': '21.3877',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Čučer-Sandevo',
    'capital': 'admin',
    'population': '752',
    'population_proper': '752',
  },
  {
    'city': 'Karbinci',
    'latitude': '41.8167',
    'longitude': '22.2375',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Karbinci',
    'capital': 'admin',
    'population': '673',
    'population_proper': '673',
  },
  {
    'city': 'Star Dojran',
    'latitude': '41.1865',
    'longitude': '22.7203',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Dojran',
    'capital': 'admin',
    'population': '363',
    'population_proper': '363',
  },
  {
    'city': 'Ilinden',
    'latitude': '41.9945',
    'longitude': '21.5800',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Ilinden',
    'capital': 'admin',
    'population': '',
    'population_proper': '',
  },
  {
    'city': 'Makedonska Kamenica',
    'latitude': '42.0208',
    'longitude': '22.5876',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Makedonska Kamenica',
    'capital': 'admin',
    'population': '',
    'population_proper': '',
  },
  {
    'city': 'Resen',
    'latitude': '41.0893',
    'longitude': '21.0109',
    'country': 'Macedonia',
    'iso2': 'MK',
    'admin_name': 'Resen',
    'capital': 'admin',
    'population': '',
    'population_proper': '',
  },
]
