export const carLights = [
  {
    'name': 'Engine Temperature Warning Light',
    'description': 'Indicator light means the engine temperature has exceeded normal limitsCheck coolant level, fan operation, radiator cap, coolant leaks',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2019/06/GOFAR_car-dashboard-symbols-engine-temperature-warning-light.jpg',
    'image_path': require(
      '../assets/car-light/Engine_Temperature_Warning_Light.jpg'),
  },
  {
    'name': 'Battery Charge Warning Light',
    'description': 'Indicator light means that the car’s charging system is short of power or is not charging properlyIt normally indicates a problem with the battery itself or the alternator',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-battery-charge.jpg',
    'image_path': require(
      '../assets/car-light/Battery_Charge_Warning_Light.jpg'),
  },
  {
    'name': 'Oil Pressure Warning Light',
    'description': 'Indicator light means loss of oil pressure, meaning lubrication is low or lost completelyImmediately check the oil level and pressure',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/283092_Car-Dashboard-Symbols_oil-pressure_090618.jpg',
    'image_path': require('../assets/car-light/Oil_Pressure_Warning_Light.jpg'),
  },
  {
    'name': 'Brake Warning Light',
    'description': 'Indicator light turns on when the handbrake is onIf it lit continuously, it means that hydraulic pressure has been lost in one side of the brake system or that the fluid level in the master cylinder is dangerously low (due to a leak somewhere in the brake system)',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake.jpg',
    'image_path': require('../assets/car-light/Brake_Warning_Light.jpg'),
  },
  {
    'name': 'Transmission Temperature',
    'description': 'Indicator light means the engine temperature has exceeded normal limitsCheck coolant level, fan operation,radiator cap, coolant leaks',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-transmission-temp.jpg',
    'image_path': require('../assets/car-light/Transmission_Temperature.jpg'),
  },
  {
    'name': 'Tire Pressure Warning Light',
    'description': 'Indicator light means the pressure is low in one of your tires',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-time-pressure.jpg',
    'image_path': require(
      '../assets/car-light/Tire_Pressure_Warning_Light.jpg'),
  },
  {
    'name': 'Traction Control Off',
    'description': 'Indicator light means that the vehicles TCS (traction control system) has been deactivated.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-traction-control-off.jpg',
    'image_path': require('../assets/car-light/Traction_Control_Off.jpg'),
  },
  {
    'name': 'Steering Wheel Lock',
    'description': 'Indicator light means your steering wheel is locked and can not be movedTo turn off the steering lock, insert the key into the ignition and turn it to at least the first position while turning the steering wheel in either direction',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-steering-wheel-lock.jpg',
    'image_path': require('../assets/car-light/Steering_Wheel_Lock.jpg'),
  },
  {
    'name': 'Trailer Tow Hitch Warning',
    'description': 'Indicator lights mean that the tow hitch is unlocked or that there’s an issue with the lighting system.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-trailer-tow-hitch-warning.jpg',
    'image_path': require('../assets/car-light/Trailer_Tow_Hitch_Warning.jpg'),
  },
  {
    'name': 'Traction Control Light',
    'description': 'Indicator light turns on when the vehicle TCS (traction control system) is activated.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-traction-control-light.jpg',
    'image_path': require('../assets/car-light/Traction_Control_Light.jpg'),
  },
  {
    'name': 'Service Vehicle Soon',
    'description': 'Indicator light turns on when there is a fault condition in an area of the vehicle chassis systems such as—the anti-lock (ABS) brake system, the traction control (TCS) system, the electronic suspension system, or the brake hydraulic system',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-sevice-vehicle-soon.jpg',
    'image_path': require('../assets/car-light/Service_Vehicle_Soon.jpg'),
  },
  {
    'name': 'Security Alert',
    'description': 'Indicator light will turn on momentarily if the ignition switch is locked and will need the proper',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-security-alert.jpg',
    'image_path': require('../assets/car-light/Security_Alert.jpg'),
  },
  {
    'name': 'Side Airbag',
    'description': 'Indicator light means a fault with the side airbag',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-side-airbag.jpg',
    'image_path': require('../assets/car-light/Side_Airbag.jpg'),
  },
  {
    'name': 'Reduced Power Warning',
    'description': 'Indicator light means that the Engine Computer has limited engine power output.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-reduced-power-warning.jpg',
    'image_path': require('../assets/car-light/Reduced_Power_Warning.jpg'),
  },
  {
    'name': 'Seat Belt Indicator',
    'description': 'Indicator light means that a seat belt has not been secured for a passenger in the vehicle.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-seat-belt.jpg',
    'image_path': require('../assets/car-light/Seat_Belt_Indicator.jpg'),
  },
  {
    'name': 'Press Clutch Pedal',
    'description': 'Indicator to push the clutch',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-press-clutch-pedal.jpg',
    'image_path': require('../assets/car-light/Press_Clutch_Pedal.jpg'),
  },
  {
    'name': 'Powertrain Fault',
    'description': 'Indicator light turns on when a powertrain or AWD fault has been detectedContact your mechanic as soon as possible.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-powertrain-fault.jpg',
    'image_path': require('../assets/car-light/Powertrain Fault.jpg'),
  },
  {
    'name': 'Power Steering Warning Light',
    'description': 'Indicator light turns on if there is an issue with the power steering system, and will be disabled until fixed.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-power-steering-warning.jpg',
    'image_path': require(
      '../assets/car-light/Power_Steering_Warning_Light.jpg'),
  },
  {
    'name': 'Press Brake Pedal',
    'description': 'Indicator to push the brake pedal',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-press-brake-pedal.jpg',
    'image_path': require('../assets/car-light/Press_Brake_Pedal.jpg'),
  },
  {
    'name': 'Parking Brake Light',
    'description': 'Indicator light means park brake is on',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-parking-brake-light.jpg',
    'image_path': require('../assets/car-light/Parking_Brake_Light.jpg'),
  },
  {
    'name': 'Overdrive Light',
    'description': 'Indicator light means that the vehicle’s overdrive system has been manually turned off.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-overdrive-light.jpg',
    'image_path': require('../assets/car-light/Overdrive_Light.jpg'),
  },
  {
    'name': 'Oil Change Reminder',
    'description': 'Indicator light means that oil life has expired',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-oil-change.jpg',
    'image_path': require('../assets/car-light/Oil_Change_Reminder.jpg'),
  },
  {
    'name': 'Master Warning Light',
    'description': 'Indicator light usually accompanied by another warning light and indicates that one or more warning systems have been detected.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-master-warning.jpg',
    'image_path': require('../assets/car-light/Master_Warning_Light.jpg'),
  },
  {
    'name': 'Information Warning Light',
    'description': 'Indicator light will turn on when a new message is stored in the information display. It will be red or amber in color depending on the severity of the message and will remain on until the cause of the message has been rectified.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-information-light-warning.jpg',
    'image_path': require('../assets/car-light/Information_Warning_Light.jpg'),
  },
  {
    'name': 'Icy Road Warning Light',
    'description': 'Indicator light turns on when the outside air starts to reach freezing temperatures, around 35°F or 3°C.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-icy-road-warning-light.jpg',
    'image_path': require('../assets/car-light/Icy_Road_Warning_Light.jpg'),
  },
  {
    'name': 'Gas/Fuel Cap',
    'description': 'Indicator light turns on if the gas/fuel cap is not properly tightened.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-gas-cap.jpg',
    'image_path': require('../assets/car-light/Gas_Fuel_Cap.jpg'),
  },
  {
    'name': 'ESP Fault/Traction Control Malfunction',
    'description': 'Indicator light means that there is a problem with the vehicle’s traction control.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-esp-fault-traction-control-malfunction.jpg',
    'image_path': require(
      '../assets/car-light/ESP_Fault_Traction_Control_Malfunction.jpg'),
  },
  {
    'name': 'Electric Park Brake',
    'description': 'Indicator light turns on when the electric parking brake has a malfunction.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-electric-park-brake.jpg',
    'image_path': require('../assets/car-light/Electric_Park_Brake.jpg'),
  },
  {
    'name': 'Distance Warning',
    'description': 'Indicator light means that a vehicle in front is too close or is being approached too quickly, or that a stationary obstacle exists in the direction of travel.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-distance-warning.jpg',
    'image_path': require('../assets/car-light/Distance_Warning.jpg'),
  },
  {
    'name': 'Clogged Air Filter',
    'description': 'Indicator light turns on when there is reduced airflow to the engineHave the air filter replaced or inspected.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-clogged-air-filter.jpg',
    'image_path': require('../assets/car-light/Clogged_Air_Filter.jpg'),
  },
  {
    'name': 'Child Safety Lock',
    'description': 'Indicator light means child safety lock is active',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-child-safety-lock.jpg',
    'image_path': require('../assets/car-light/Child_Safety_Lock.jpg'),
  },
  {
    'name': 'Check Engine or Malfunction Indicator Light (MIL)',
    'description': 'Indicator light turns on whenever the engine is turned on to check the bulb. If the light stays illuminated, the car’s diagnostic systems have detected a malfunction that needs to be investigated',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-check-engine.jpg',
    'image_path': require(
      '../assets/car-light/Check_Engine_or_Malfunction_Indicator_Light_(MIL).jpg'),
  },
  {
    'name': 'Catalytic Converter Warning',
    'description': 'Indicator light means the catalytic converter is either overheating or not operating as intended.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-catalytic-converter-warning.jpg',
    'image_path': require(
      '../assets/car-light/Catalytic_Converter_Warning.jpg'),
  },
  {
    'name': 'Brake Fluid',
    'description': 'Indicator light means that the brake fluid level is low',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake-fluid.jpg',
    'image_path': require('../assets/car-light/Brake_Fluid.jpg'),
  },
  {
    'name': 'Brake Pad Warning',
    'description': 'Indicator light means that the brake pads are worn',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake-pad.jpg',
    'image_path': require('../assets/car-light/Brake_Pad_Warning.jpg'),
  },
  {
    'name': 'Brake Lights Warning',
    'description': 'Indicator light means an exterior brake light bulb is defectiveCheck the operation of all the exterior brake light',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake-lights-warning.jpg',
    'image_path': require('../assets/car-light/Brake_Lights_Warning.jpg'),
  },
  {
    'name': 'Automatic Gearbox Warning',
    'description': 'Indicator light means there\'s a gearbox/transmission malfunction.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-automatic-gearbox-warning.jpg',
    'image_path': require('../assets/car-light/Automatic_Gearbox_Warning.jpg'),
  },
  {
    'name': 'Anti-lock Braking System (ABS)',
    'description': 'Indicator light means there may be a malfunction in the ABS system',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-anti-lock-braking-system.jpg',
    'image_path': require(
      '../assets/car-light/Anti-lock_Braking_System_(ABS).jpg'),
  },
  {
    'name': 'All Wheel Drive (AWD/4WD)',
    'description': 'Indicator light turns on when there is a malfunction with the 4WD system.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-all-wheel-drive.jpg',
    'image_path': require('../assets/car-light/All_Wheel_Drive_(AWD_4WD).jpg'),
  },
  {
    'name': 'Airbag Indicator',
    'description': 'Indicator light turns on when the front airbag is switched off. If this lamp lights up or flashes there is a fault in the airbag or seatbelt system',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-airbag.jpg',
    'image_path': require('../assets/car-light/Airbag_Indicator.jpg'),
  },
  {
    'name': 'Airbag Deactivated',
    'description': 'Indicator light turns on when there is a fault in the rear spoiler system.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-airbag-deactivated.jpg',
    'image_path': require('../assets/car-light/Airbag_Deactivated.jpg'),
  },
  {
    'name': 'Adaptive Suspension Dampers',
    'description': 'Indicator light means there is a need to contact an authorised repairer.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adaptive-suspension-dampers.jpg',
    'image_path': require(
      '../assets/car-light/Adaptive_Suspension_Dampers.jpg'),
  },
  {
    'name': '4 Wheel Drive (4WD) LOCK Indicator Light',
    'description': 'Indicator light means that the vehicle\'s 4WD Lock mode is activated.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-4WD-lock-indicator.jpg',
    'image_path': require(
      '../assets/car-light/4_Wheel_Drive_(4WD)_LOCK_Indicator_Light.jpg'),
  },
  {
    'name': 'Air Suspension',
    'description': 'Indicator light means that there is a problem with the air suspension bags, likely due to a leak or inflation issue.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-air-suspension.jpg',
    'image_path': require('../assets/car-light/Air_Suspension.jpg'),
  },
  {
    'name': 'Low Beam Indicator Light',
    'description': 'Indicator light means that the vehicles dipped beam is on',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-low-beam-indicator-light.jpg',
    'image_path': require('../assets/car-light/Low_Beam_Indicator_Light.jpg'),
  },
  {
    'name': 'Lamp Out',
    'description': 'Indicator light means that there is an exterior light on the vehicle that is not functioning properly.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-lamp-out.jpg',
    'image_path': require('../assets/car-light/Lamp_Out.jpg'),
  },
  {
    'name': 'High Beam Light Indicator',
    'description': 'Indicator light means your car’s high beam headlights are on, or if the high beam flash function is used.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-high-beam-light-indicator.jpg',
    'image_path': require('../assets/car-light/High_Beam_Light_Indicator.jpg'),
  },
  {
    'name': 'Headlight Range Control',
    'description': 'Indicator light turns on if there is an issue detected with the headlight range control system.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-headlight-range-control.jpg',
    'image_path': require('../assets/car-light/Headlight_Range_Control.jpg'),
  },
  {
    'name': 'Front Fog Lights',
    'description': 'Indicator light means front fog lights are turned on',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-front-fog-light.jpg',
    'image_path': require('../assets/car-light/Front_Fog_Lights.jpg'),
  },
  {
    'name': 'Exterior Light Fault',
    'description': 'Indicator light means any exterior light on your car isn’t working',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-exterior-light-fault.jpg',
    'image_path': require('../assets/car-light/Exterior_Light_Fault.jpg'),
  },
  {
    'name': 'Auto High Beam',
    'description': 'Indicator light means the Auto High Beam system has switched on high beam headlights.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-auto-high-beam.jpg',
    'image_path': require('../assets/car-light/Auto_High_Beam.jpg'),
  },
  {
    'name': 'Adaptive Light System',
    'description': 'Indicator light will lit when adaptive headlights are turned on',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adaptive-light-system.jpg',
    'image_path': require('../assets/car-light/Adaptive_Light_System.jpg'),
  },
  {
    'name': 'Side Light Indicator',
    'description': 'Indicator light will turn on when the normal headlights are in use',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-side-light-indicator-light.jpg',
    'image_path': require('../assets/car-light/Side_Light_Indicator.jpg'),
  },
  {
    'name': 'Rear Fog Lights Switched On',
    'description': 'Indicator light means rear fog lights are on',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-rear-fog-lights.jpg',
    'image_path': require(
      '../assets/car-light/Rear_Fog_Lights_Switched_On.jpg'),
  },
  {
    'name': 'Rain and Light Sensor',
    'description': 'Indicator light means there is an issue with the sensor systemThe wipers and lights will not function',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-rain-and-light-sensor.jpg',
    'image_path': require('../assets/car-light/Rain_and_Light_Sensor.jpg'),
  },
  {
    'name': 'Windshield Defrost',
    'description': '        Indicator light means that the window defrost is in operation.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-windshield-defrost.jpg',
    'image_path': require('../assets/car-light/Windshield_Defrost.jpg'),
  },
  {
    'name': 'Washer Fluid Reminder',
    'description': 'Indicator light indicates if the windscreen washer fluid reservoir is nearly emptyFill the washer fluid reservoir.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-water-fluid-reminder.jpg',
    'image_path': require('../assets/car-light/Washer_Fluid_Reminder.jpg'),
  },
  {
    'name': 'Rear Window Defrost',
    'description': 'Indicator light means that the rear window defrost is in operation',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-rear-window-defrost.jpg',
    'image_path': require('../assets/car-light/Rear_Window_Defrost.jpg'),
  },
  {
    'name': 'Low Fuel Level',
    'description': 'Indicator light means that the car is running low on fuel and will soon need a refill.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-low-fuel-level.jpg',
    'image_path': require('../assets/car-light/Low_Fuel_Level.jpg'),
  },
  {
    'name': 'Key Not in Vehicle',
    'description': 'Indicator light means the key is not in the car',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-key-not-in-vehicle.jpg',
    'image_path': require('../assets/car-light/Key_Not_in_Vehicle.jpg'),
  },
  {
    'name': 'Hood/Bonnet Open',
    'description': 'Indicator light means that the car hood is not closed properly',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-hood-bonnet-open.jpg',
    'image_path': require('../assets/car-light/Hood_Bonnet_Open.jpg'),
  },
  {
    'name': 'Hazard Lights On',
    'description': 'Indicator light means hazard lights are turned on',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-hazard-lights-on.jpg',
    'image_path': require('../assets/car-light/Hazard_Lights_On.jpg'),
  },
  {
    'name': 'Fan',
    'description': 'Indicator light means that the internal ventilation/fan is in operation.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-fan-green.jpg',
    'image_path': require('../assets/car-light/Fan.jpg'),
  },
  {
    'name': 'Door Ajar',
    'description': 'Indicator light turns on when one or more doors of the car are not shut properly.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-door-ajar.jpg',
    'image_path': require('../assets/car-light/Door_Ajar.jpg'),
  },
  {
    'name': 'Direction/Signal Indicators',
    'description': 'Indicator light means that one of the turn signals (left or right) has been activated.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-direction-signal-indicators.jpg',
    'image_path': require(
      '../assets/car-light/Direction_Signal_Indicators.jpg'),
  },
  {
    'name': 'Car on Ramp',
    'description': 'Indicator light means that the vehicle is on a ramp/jack system',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-car-on-ramp.jpg',
    'image_path': require('../assets/car-light/Car_on_Ramp.jpg'),
  },
  {
    'name': 'Recirculated Cabin Air',
    'description': '        Indicator light means that the vehicle’s ventilation system is recirculating air from within the vehicle,',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-recirculated-cabin-air.jpg',
    'image_path': require('../assets/car-light/Recirculated_Cabin_Air.jpg'),
  },
  {
    'name': 'Rear Spoiler Warning',
    'description': 'Indicator light turns on when there is a fault in the rear spoiler system.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-rear-spoiler-warning.jpg',
    'image_path': require('../assets/car-light/Rear_Spoiler_Warning.jpg'),
  },
  {
    'name': 'Parking with Park Assist Pilot',
    'description': 'Indicator light means PAP (Park Assist Pilot) is activated',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-parking-with-park-assist-pilot.jpg',
    'image_path': require(
      '../assets/car-light/Parking_with_Park_Assist_Pilot.jpg'),
  },
  {
    'name': 'Lane Departure Warning',
    'description': 'Indicator light means the vehicle is detected to be moving out of its current lane without signalling.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-lane-departure-warning.jpg',
    'image_path': require('../assets/car-light/Lane_Departure_Warning.jpg'),
  },
  {
    'name': 'Lane Assist',
    'description': 'Indicator light turns on when the lane assist system is switched on and road markings can be detected.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-lane-assist.jpg',
    'image_path': require('../assets/car-light/Lane_Assist.jpg'),
  },
  {
    'name': 'Key Fob Battery Low',
    'description': 'Indicator light lets you know when your key fob battery needs to be changed and replaced, so you can continue using',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-key-fob-battery-low.jpg',
    'image_path': require('../assets/car-light/Key_Fob_Battery_Low.jpg'),
  },
  {
    'name': 'Ignition Switch Warning',
    'description': 'Indicator light means there’s an issue with the ignition system or the car keyIt could be due to a glitch or worn out key',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-ignition-switch-warning.jpg',
    'image_path': require('../assets/car-light/Ignition_Switch_Warning.jpg'),
  },
  {
    'name': 'Hill Descent Control',
    'description': 'Indicator light turns on when the system is activated and helps you maintain a specific speed while driving down a hill',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-hill-descent-control.jpg',
    'image_path': require('../assets/car-light/Hill_Descent_Control.jpg'),
  },
  {
    'name': 'Forward Collision Warning',
    'description': 'Indicator light turns on when a potential collision is detected',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-forward-collision.jpg',
    'image_path': require('../assets/car-light/Forward_Collision_Warning.jpg'),
  },
  {
    'name': 'Eco Driving Indicator',
    'description': 'Indicator light will turn on when the Eco function is activated',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-eco-driving-indicator.jpg',
    'image_path': require('../assets/car-light/Eco_Driving_Indicator.jpg'),
  },
  {
    'name': 'Cruise Control',
    'description': 'Indicator light means the cruise control system is activated',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-cruise-control.jpg',
    'image_path': require('../assets/car-light/Cruise_Control.jpg'),
  },
  {
    'name': 'Convertible Roof Warning Light',
    'description': 'Indicator light will turn on while the roof is either opening or closing. If the lamp is lit continuously the roof is not fully opened, or there is a fault in the system',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-convertible-roof-warning-light.jpg',
    'image_path': require(
      '../assets/car-light/Convertible_Roof_Warning_Light.jpg'),
  },
  {
    'name': 'Brake Hold Indicator Light',
    'description': 'Indicator light means that the brake hold system is functioning properly.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-brake-hold-indicator.jpg',
    'image_path': require('../assets/car-light/Brake_Hold_Indicator_Light.jpg'),
  },
  {
    'name': 'Blind Spot Indicator Light',
    'description': 'Indicator light turns on when a vehicle or obstruction is detected in the blind spot.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-blind-spot-indicator.jpg',
    'image_path': require('../assets/car-light/Blind_Spot_Indicator_Light.jpg'),
  },
  {
    'name': 'Auto Windscreen Wiping',
    'description': 'Indicator light means the windscreen wipers are in operation on Automatic mode.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-auto-windscreen-wiping.jpg',
    'image_path': require('../assets/car-light/Auto_Windscreen_Wiping.jpg'),
  },
  {
    'name': 'Automatic Emergency Braking (AEB)',
    'description': 'Indicator light turns on when the AEB system is turned off or when the radar sensor or cover is blocked with dirt or snow',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-automatic-emegency-braking.jpg',
    'image_path': require(
      '../assets/car-light/Automatic_Emergency_Braking_(AEB).jpg'),
  },
  {
    'name': 'Adaptive Cruise Control',
    'description': 'Indicator light means that the ACC (Adaptive Cruise Control) is in operation.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adaptive-cruise-control.jpg',
    'image_path': require('../assets/car-light/Adaptive_Cruise_Control.jpg'),
  },
  {
    'name': 'Winter Mode',
    'description': 'Indicator light lets you know you’re driving on winter mode',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-winter-mode.jpg',
    'image_path': require('../assets/car-light/Winter_Mode.jpg'),
  },
  {
    'name': 'Start/Stop Warning Light',
    'description': 'Indicator light turns on to inform the driver that Intelligent Stop / Start system is active and the engine has been shut down',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-start-stop-warning.jpg',
    'image_path': require('../assets/car-light/Start_Stop_Warning_Light.jpg'),
  },
  {
    'name': 'Speed Limiter',
    'description': 'Indicator light means that the speed limiter function is activated',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-speed-limiter.jpg',
    'image_path': require('../assets/car-light/Speed_Limiter.jpg'),
  },
  {
    'name': 'Seat Temperature',
    'description': 'Indicator light means that the air flow is distributed between front side window, windscreen and footwell de-misting vents',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-seat-temperature.jpg',
    'image_path': require('../assets/car-light/Seat_Temperature.jpg'),
  },
  {
    'name': 'Glow Plug Indicator',
    'description': 'Indicator light means that the engine’s glow plugs are warming up and the engine should not be started until the light goes out. If it flashes, an issue has been detected, such as a worn out glow plug',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-glow-plug.jpg',
    'image_path': require('../assets/car-light/Glow_Plug_Indicator.jpg'),
  },
  {
    'name': 'Fuel Filter Warning',
    'description': 'Indicator light means that the diesel fuel filter is full, and needs to be emptied to avoid engine damage.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-fuel-filter-warning.jpg',
    'image_path': require('../assets/car-light/Fuel_Filter_Warning.jpg'),
  },
  {
    'name': 'Exhaust Fluid',
    'description': 'Indicator light means that the diesel exhaust fluid reservoir is low on fluid.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-exhaust-fluid.jpg',
    'image_path': require('../assets/car-light/Exhaust_Fluid.jpg'),
  },
  {
    'name': 'AdBlue Tank is Empty',
    'description': 'Indicator light means you have to fill the tank with more exhaust fluid.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adblue-tank-empty.jpg',
    'image_path': require('../assets/car-light/AdBlue_Tank_is_Empty.jpg'),
  },
  {
    'name': 'AdBlue Malfunction',
    'description': 'Indicator light means either the AdBlue system is malfunctioning or the system is not filled with the standard liquid',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-adblue-tank-malfunction.jpg',
    'image_path': require('../assets/car-light/AdBlue_Malfunction.jpg'),
  },
  {
    'name': 'Water Fluid Filter Warning',
    'description': 'Indicator light means water in fuel filter has reached maximum capacityDrain the water from filter.',
    'image_url': 'https://www.gofar.co/wp-content/uploads/2018/10/car-dashboard-symbols-water-fluid-filter.jpg',
    'image_path': require('../assets/car-light/Water_Fluid_Filter_Warning.jpg'),
  },
]
